name = ArthurCompanion
version = 0.1.0
mainclass = furhatos.app.arthurcompanion.ArthurCompanionSkill
language = en-US
logLevel = INFO
requiresVersion = false
requiresCamera = false
requiresSpeaker = false
requiresMicrophone = false
requiresRecognizer = false
